### ISSUE TITLE
autoinstall yaml ignored, can't find docs

### ISSUE THREAD

**Issue by GethDeeo** [ubuntu/WSL#401]
### cmd /c ver

Microsoft Windows [Version 10.0.22621.1778]

### wsl --status

```
Default Distribution: Ubuntu-22.04
Default Version: 2
WSL1 is not supported with your current machine configuration.
Please enable the "Windows Subsystem for Linux" optional component to use WSL1.
```

### Did the problem occur during installation?

- [X] Yes

### What happened?

I have a simple autoinstall yaml file in current directory, containing:
- `version`
- `identity`
- `packages`
- `late-commands`
- `user-data` (mainly for `write-files`)

I ran this command: `ubuntu2204.exe install --root --autoinstall .\simple.yaml --ui=none`  
(I've tried it without `--root` with same results.)  
It's like the whole file is ignored, I don't know where to look for additional logs. I just see the 10 minutes cloud-init wait gap in the logs and that's it.

I don't know if this feature is working, where the docs are for it, what the current limitations are, plans for the future, etc.  
It would be nice to be able to preconfigure wsl Ubuntu environment very similar to my VM and barebone installations - obviously I wouldn't touch some stuff like `network` or `storage`.

### What was expected?

Ubuntu is installed with configuration according to autoinstall yaml file.

### Steps to reproduce

I've used this as contents of autoinstall yaml file:

```yaml
#cloud-config
autoinstall:
  version: 1
  identity:
    realname: whatever
    username: geth
    password: '$1$Dct4aGTo$p1OettH8tlj74w4g5AVN21'
  packages:
    - mc
    - jq
  late-commands:
    - - curtin
      - in-target
      - --
      - sh
      - -c
      - |
        printf 'TODO late-commands\n' >> /var/tmp/testy
  user-data:
    package_update: true
    package_upgrade: true
    ssh_publish_hostkeys: { enabled: false }
    write_files:
      - path: /etc/skel/.vimrc
        content: |
          let &t_SI .= "\<Esc>[?2004h"
          let &t_EI .= "\<Esc>[?2004l"
          inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()
          
          function! XTermPasteBegin()
            set pastetoggle=<Esc>[201~
            set paste
            return ""
          endfunction
```

### Additional information

[subiquity-server-debug.log](https://github.com/ubuntu/WSL/files/11704689/subiquity-server-debug.log)
